#!/bin/bash

# Source config script
source arguments_param
source folder.config 

# Step 1: recall_demux
# dorado - recall and demux
# CORE PARAMETERS: sourcedir, 
# INPUT: pod5dir
# WORK: basecall
# OUTPUT: null
# PROCESS - File transfer
sbatch -d singleton --error="${log}/1_recall-demux_%J.err" --output="${log}/1_recall-demux_%J.out" --job-name=${runname} --partition=${gpu} "${moduledir}/1_recall-demux.sh"

samples=$( tail -n +2 ${sourcedir}/${metadata} | cut -f1 -d,)

export samples
export sample_array=($samples)
sample_number=${#sample_array[@]}
sample_number=$(($sample_number - 1))

# Step 2: convert to fastq
# CORE PARAMETERS: modules, fastqdir, workdir
# INPUT: basecalldir
# WORK: fastqdir
# OUTPUT: null
# PROCESS - bedtoools
sbatch -d singleton --error="${log}/2_recall-fastq_%J.err" --output="${log}/2_recall-fastq%J.out" --job-name=${runname} --partition=${node} "${moduledir}/2_recall-fastq.sh"

# Step 3: Renaming files
# CORE PARAMETERS: modules, fastqdir, renameddir
# INPUT: fastqdir
# WORK: 
# OUTPUT: null
# PROCESS - 
sbatch -d singleton --error="${log}/3_recall-rename%J.err" --output="${log}/3_recall-rename%J.out"  --job-name=${runname} --partition=${node} "${moduledir}/3_recall-rename.sh"  


# Step 4: FastQC 
# CORE PARAMETERS: modules, renameddir, qcdir
# INPUT: renameddir
# WORK: qcdir
# OUTPUT: null
# PROCESS - FastQC raw data
sbatch -d singleton --error="${log}/4_recall-QC%J.err" --output="${log}/4_recall-QC%J.out" --job-name=${runname} --partition=${node} "${moduledir}/4_recall-QC.sh"

#Part 2: taxonamy classification using emu

# Step 5: Miniforge install
# CORE PARAMETERS: modules, miniforgedir, workdir 
# INPUT: N/A
# WORK: miniforgedir
# OUTPUT: null
# PROCESS - 
sbatch -d singleton --error="${log}/5_emu-install%J.err" --output="${log}/5_emu-install%J.out" --job-name=${runname} --partition=${node} "${moduledir}/5_emu-install.sh"

# Step 6: Database install
# CORE PARAMETERS: modules, workdir, EMU_DATA_DIR
# INPUT: N/A
# WORK: EMU_DATA_DIR
# OUTPUT: null
# PROCESS -
sbatch -d singleton --error="${log}/6_emu-database%J.err" --output="${log}/6_emu-database%J.out" --job-name=${runname} --partition=${node} "${moduledir}/6_emu-database.sh"

# Step 7: emu batch
# CORE PARAMETERS: modules, workdir, fastqcdir
# INPUT: Fastqc files
# WORK: reportdir
# OUTPUT: null
# PROCESS -
sbatch -d singleton --error="${log}/7A_emu-array%J.err" --output="${log}/7A_emu-array%J.out" --"array=0-${sample_number}%12" --job-name=${runname} --partition=${node} "${moduledir}/7A_emu-array.sh"

sbatch -d singleton --error="${log}/7B_emu-combine%J.err" --output="${log}/7B_emu-combine%J.out" --job-name=${runname} --partition=${node} "${moduledir}/7B_emu-combine.sh"

# Step 8: conversion to ranacapa format
# CORE PARAMETERS: modules, workdir, scripts, reportdir
# INPUT: reportdir and metadata file
# WORK: ranacapa
# OUTPUT: null
# PROCESS -
sbatch -d singleton --error="${log}/8_SARTools%J.err" --output="${log}/8_SARTools%J.out" --job-name=${runname} --partition=${node} "${moduledir}/8_SARTools.sh"

